name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f552978b887f7b1a7354d3445fea7c54e2ecb297519de5b430bb96c155b501dd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
