name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf90d5117f4fefb3b2c9161ffb426b0878ce93b82bd1ce0431c4d9a856a88b4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
