name = "Young Again"
author = "IvieThePlant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f9326a57458c2898aabe6699b5eaff54687c0929d3f4c13cac5a602f65934b5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
